spring.application.name=cloud

server.port=8080

spring.datasource.url=jdbc:mysql://database-1.cno64q0e27or.sa-east-1.rds.amazonaws.com:3306/aws_cloud?sslMode=VERIFY_IDENTITY&trustCertificateKeyStoreUrl=file:./rds-truststore.jks&trustCertificateKeyStorePassword=changeit
spring.datasource.username=admin
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true